version: "3"
services:
  was:
    image: gamja123/second-hand-nginx
    container_name: was-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - application

  application:
    build: .
    image: gamja123/second-hand
    container_name: was-application
    ports:
      - 8080:8080
    expose:
      - 8080
