# .github/workflows/chromatic.yml

# Workflow name
name: "ìŠ¤í† ë¦¬ë¶ Chromatic ìë™ ë°°í¬"

# Event for the workflow
on:
  push:
    branches: [dev-fe]
    # paths: ["fe/src/components/**"]

env:
  working-directory: "./fe"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: lts/Hydrogen

      - name: Cache node modules
        uses: actions/cache@v2.1.8
        # í•´ë‹¹ stepì„ ëŒ€í‘œí•˜ëŠ” idë¥¼ ì„¤ì •í•  ìˆ˜ë„ ìˆë‹¤. í•´ë‹¹ ê°’ì€ ë’¤ì˜ stepì—ì„œ ì‚¬ìš©í•œë‹¤.
        id: cache
        with:
          # node_modulesë¼ëŠ” í´ë”ë¥¼ ê²€ì‚¬í•˜ì—¬
          path: node_modules
          # ì•„ë˜ í‚¤ê°’ìœ¼ë¡œ cacheê°€ ë¼ìˆëŠ”ì§€ í™•ì¸í•œë‹¤.
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Run Chromatic
        run: npm run chromatic -- --exit-zero-on-changes
        working-directory: ${{ env.working-directory }}

      - name: Publish to Chromatic
        #ğŸ‘‡ Adds Chromatic as a step in the workflow
        uses: chromaui/action@v1
        with:
          #ğŸ‘‡ Chromatic projectToken,
          project-token: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          exit-zero-on-changes: true